/**
 * Internationalization support for demosmith-mcp
 */

export type Language = 'en' | 'zh';

interface Translations {
  // Document titles
  tutorialTitle: string;
  guideTitle: string;
  narrationTitle: string;

  // Step actions
  actions: {
    navigate: string;
    click: string;
    fill: string;
    select: string;
    screenshot: string;
    wait: string;
    scroll: string;
    pressKey: string;
    drag: string;
    upload: string;
    hover: string;
    assert: string;
    newTab: string;
    switchTab: string;
    closeTab: string;
  };

  // UI labels
  ui: {
    step: string;
    steps: string;
    duration: string;
    previous: string;
    next: string;
    complete: string;
    restart: string;
    progress: string;
    tableOfContents: string;
    generatedBy: string;
    tutorialComplete: string;
    successfullyCompleted: string;
  };

  // Narration templates
  narration: {
    intro: (title: string) => string;
    stepPrefix: (num: number) => string;
    navigate: (url: string) => string;
    click: (name: string) => string;
    fill: (name: string, value: string) => string;
    select: (name: string, value: string) => string;
    screenshot: () => string;
    wait: (condition: string) => string;
    scroll: (direction: string) => string;
    pressKey: (key: string) => string;
    drag: (from: string, to: string) => string;
    upload: (fileName: string) => string;
    hover: (name: string) => string;
    assert: (type: string, result: boolean) => string;
    outro: () => string;
  };
}

const translations: Record<Language, Translations> = {
  en: {
    tutorialTitle: 'Interactive Tutorial',
    guideTitle: 'Step-by-Step Guide',
    narrationTitle: 'Narration Script',

    actions: {
      navigate: 'Navigate',
      click: 'Click',
      fill: 'Fill',
      select: 'Select',
      screenshot: 'Screenshot',
      wait: 'Wait',
      scroll: 'Scroll',
      pressKey: 'Press Key',
      drag: 'Drag',
      upload: 'Upload',
      hover: 'Hover',
      assert: 'Verify',
      newTab: 'New Tab',
      switchTab: 'Switch Tab',
      closeTab: 'Close Tab',
    },

    ui: {
      step: 'Step',
      steps: 'steps',
      duration: 'Duration',
      previous: 'Previous',
      next: 'Next',
      complete: 'Complete',
      restart: 'Start Over',
      progress: 'Progress',
      tableOfContents: 'Table of Contents',
      generatedBy: 'Generated by demosmith',
      tutorialComplete: 'Tutorial Complete!',
      successfullyCompleted: 'You have successfully completed all',
    },

    narration: {
      intro: (title) => `Welcome to this tutorial: ${title}. Let's walk through the steps together.`,
      stepPrefix: (num) => `Step ${num}:`,
      navigate: (url) => `First, navigate to ${url}.`,
      click: (name) => `Click on the "${name}" element.`,
      fill: (name, value) => `Enter "${value}" in the ${name} field.`,
      select: (name, value) => `Select "${value}" from the ${name} dropdown.`,
      screenshot: () => `Here's what the screen looks like at this point.`,
      wait: (condition) => `Wait for ${condition}.`,
      scroll: (direction) => `Scroll ${direction} on the page.`,
      pressKey: (key) => `Press the ${key} key.`,
      drag: (from, to) => `Drag the element from ${from} to ${to}.`,
      upload: (fileName) => `Upload the file "${fileName}".`,
      hover: (name) => `Hover over the "${name}" element.`,
      assert: (type, result) => result
        ? `Verify that the ${type} check passes.`
        : `Note: The ${type} check did not pass as expected.`,
      outro: () => `That concludes this tutorial. Thank you for following along!`,
    },
  },

  zh: {
    tutorialTitle: '交互式教程',
    guideTitle: '操作指南',
    narrationTitle: '旁白脚本',

    actions: {
      navigate: '导航',
      click: '点击',
      fill: '填写',
      select: '选择',
      screenshot: '截图',
      wait: '等待',
      scroll: '滚动',
      pressKey: '按键',
      drag: '拖拽',
      upload: '上传',
      hover: '悬停',
      assert: '验证',
      newTab: '新标签页',
      switchTab: '切换标签页',
      closeTab: '关闭标签页',
    },

    ui: {
      step: '步骤',
      steps: '步',
      duration: '耗时',
      previous: '上一步',
      next: '下一步',
      complete: '完成',
      restart: '重新开始',
      progress: '进度',
      tableOfContents: '目录',
      generatedBy: '由 demosmith 自动生成',
      tutorialComplete: '教程完成！',
      successfullyCompleted: '您已成功完成全部',
    },

    narration: {
      intro: (title) => `欢迎来到本教程：${title}。让我们一起来看看操作步骤。`,
      stepPrefix: (num) => `第 ${num} 步：`,
      navigate: (url) => `首先，打开 ${url}。`,
      click: (name) => `点击"${name}"。`,
      fill: (name, value) => `在 ${name} 输入框中输入"${value}"。`,
      select: (name, value) => `从 ${name} 下拉菜单中选择"${value}"。`,
      screenshot: () => `这是当前页面的截图。`,
      wait: (condition) => `等待 ${condition}。`,
      scroll: (direction) => `向${direction === 'down' ? '下' : direction === 'up' ? '上' : direction}滚动页面。`,
      pressKey: (key) => `按下 ${key} 键。`,
      drag: (from, to) => `将元素从 ${from} 拖拽到 ${to}。`,
      upload: (fileName) => `上传文件"${fileName}"。`,
      hover: (name) => `将鼠标悬停在"${name}"上。`,
      assert: (type, result) => result
        ? `验证 ${type} 检查通过。`
        : `注意：${type} 检查未通过。`,
      outro: () => `本教程到此结束。感谢您的观看！`,
    },
  },
};

// Current language setting
let currentLanguage: Language = 'en';

/**
 * Set the current language
 */
export function setLanguage(lang: Language): void {
  currentLanguage = lang;
}

/**
 * Get the current language
 */
export function getLanguage(): Language {
  return currentLanguage;
}

/**
 * Get translations for the current language
 */
export function t(): Translations {
  return translations[currentLanguage];
}

/**
 * Get translations for a specific language
 */
export function getTranslations(lang: Language): Translations {
  return translations[lang];
}

/**
 * Get action name in current language
 */
export function getActionName(action: string): string {
  const actions = translations[currentLanguage].actions;
  return (actions as any)[action] || action;
}

/**
 * Format duration in current language
 */
export function formatDuration(ms: number): string {
  if (ms < 1000) {
    return currentLanguage === 'zh' ? `${ms} 毫秒` : `${ms}ms`;
  }
  const seconds = (ms / 1000).toFixed(1);
  return currentLanguage === 'zh' ? `${seconds} 秒` : `${seconds}s`;
}
